name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 23 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.general.svg
          output_action: gist
          committer_gist: ${{ secrets.GENERAL_GIST_ID }}
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.wakatime.svg
          output_action: gist
          committer_gist: ${{ secrets.WAKATIME_GIST_ID }}
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: "7"
          plugin_wakatime_limit: 0
          plugin_wakatime_repositories_visibility: "all"
