name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 23 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.general.svg
          output_action: gist
          committer_gist: ${{ secrets.GENERAL_GIST_ID }}
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 0, 10
          base: header, repositories
          plugin_lines: yes
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.wakatime.svg
          output_action: gist
          committer_gist: ${{ secrets.WAKATIME_GIST_ID }}
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: "7"
          plugin_wakatime_limit: 0
          plugin_wakatime_repositories_visibility: "all"
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          output_action: gist
          committer_gist: ${{ secrets.LANGUAGES_GIST_ID }}
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, makefile, qmake, lex, cmake,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
