name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 23 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
    - uses: bearbaka/metrics@master
      with:
        config_timezone: Europe/Paris

    # 
    #   - name: General
    #     uses: bearbaka/metrics@master
    #     with:
    #       filename: metrics.general.svg
    #       token: ${{ secrets.METRICS_TOKEN }}
    #       base: header, repositories
    #       plugin_lines: yes
